export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImluZ3JpZCIsImVtYWlsIjoiaW5ncmlkQGdtYWlsLmNvbSIsImlhdCI6MTcwNDIyMTU1MiwiZXhwIjoxNzA0ODI2MzUyLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.aJdZQwCe_sfGYvgeYiJR6T0s3VSHdAGbtg1iMv0j82c';
