export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImluZ3JpZCIsImVtYWlsIjoiaW5ncmlkQGdtYWlsLmNvbSIsImlhdCI6MTcwNDIyNDA2MSwiZXhwIjoxNzA0ODI4ODYxLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.Qpp4m2GPgvffAxJQotrGRLZSdNXEj37qnB5CWd6DcpA';
